### ISSUE TITLE
Knoodle not following redirects? WebID behind redirect doesn't work

### ISSUE THREAD

**Issue by bjdmeest** [KNowledgeOnWebScale/knoodle#6]
Using my webid https://ben.de-meester.org/#me gives a CORS issue (+ 302), whilst eg https://cors-test.codehappy.dev/?url=https%3A%2F%2Fben.de-meester.org%2F%23me&method=get shows no problems, probably because Knoodle isn't following redirects, any pointers on where I can start debugging/fixing?

**Comment by RubenVerborgh** [comment]
What are the CORS details? I suspect Knoodle is sending some extra headers over.
Here is my NGINX conf for my WebID:

```nginx
  # Allow authentication with profile
 location ^~ /profile {
    set $allow_origin $http_origin;
    if ($allow_origin = '') {
      set $allow_origin '*';
    }
    add_header 'Access-Control-Allow-Origin' $allow_origin;
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Headers' 'Accept, Authorization, DPop, User-Agent, Map';
    add_header 'Access-Control-Allow-Methods' 'OPTIONS, GET, HEAD';
    add_header 'Access-Control-Allow-Everything' 'Aaaaaargh';
    add_header 'Vary' 'Origin';
 }
```

**Comment by bjdmeest** [comment]
```
access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
access-control-allow-methods: PUT, GET, POST, DELETE, OPTIONS
access-control-allow-origin: *
```

But I'll change to those and see what happens first :)

**Comment by RubenVerborgh** [comment]
`access-control-allow-headers`: also add `Accept`, because RDF apps tend to have longer accept headers. And any header >128 chars needs to be listed explicitly.
